# Gradle Properties
# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
# Configure buildscript warnings to be errors
org.gradle.kotlin.dsl.allWarningsAsErrors=true
# Enable Gradle build cache
org.gradle.caching=true
# Enable Gradle configuration cache
org.gradle.configuration-cache=true

# Metadata
mod_id=crooked_crooks
mod_description=Adds its own take on crooks. They multiply drops from leaves and grass, herd sheep and pull mobs!
mod_display_name=Crooked Crooks
sources_url=https://github.com/Up-Mods/CrookedCrooks
issues_url=https://github.com/Up-Mods/CrookedCrooks/issues
license_url=https://github.com/Up-Mods/CrookedCrooks/blob/HEAD/LICENSE.md
discord_url=https://mods.upcraft.dev/discord
homepage_url=https://modrinth.com/mod/DG76dVRB

# Publishing
group=io.github.ennuil.crooked_crooks
curseforge_id=393714
modrinth_id=DG76dVRB

# Mod versioning is managed at build.gradle.kts
# Dependencies are managed at gradle/libs.versions.toml
