# The latest versions are available at https://quiltmc.org/en/usage/latest-versions/
[versions]
minecraft = "1.21.5"
parchment = "2024.12.22"

fabric_loom = "1.10.5"
fabric_loader = "0.16.10"
moddevgradle = "2.0.79"
neoforge = "21.5.0-beta"

fabric_api = "0.119.5+1.21.5"

modmenu = "14.0.0-rc.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.4", version.ref = "parchment" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }
